### PR TITLE
Add a more easy to use setup

### PR DESCRIPTION
**Pull request by J-tt**
This uses gunicorn+nginx so it's a bit more production ready than runserver.

Super easy to setup now as well, only issue is with permissions of the media folder unfortunately. 

Also uses postgres for the database :)

### CODE REVIEW

**Comment by chibicitiberiu** [comment]
Really nice 👍, thanks for the PR. I would like to keep the SQLite database, would it be too much to add an environment variable to select between 'development' and 'production' modes? This way we can keep the settings separated.

**Comment by chibicitiberiu** [comment]
I think I may have noticed an error. I think you may be running 2 instances of the server at the same time.

In _Dockerfile_, you have the line `CMD ["python", "./manage.py", "runserver", "8000", "--noreload"]` which starts the server. But you also run `init.sh` in _docker-compose.yml_, which starts the server using gunicorn.

I'm not very familiar with Docker, so I could be wrong.

**Comment by J-tt** [comment]
Ah, yeah, that's left over from my testing. I'll submit a PR to fix that.

**Comment by chibicitiberiu** [comment]
Ok, great, thanks 👍

**Comment by joshstrange** [comment]
A couple things I'd like to throw in:

* I think it would be better to only copy in the app and not the config
* I think the docker image itself should be responsible for running the init.sh and not the docker compose file
* I think the docker image should be published to docker hub from this repo (Only @chibicitiberiu can set this up, I setup a fork to build but only he or someone with repo access can do that so that it's up to date)
* Config/data should be VOLUME'd and port should be EXPOSED'd

All of this would allow for someone to do the following:

****
$ docker pull chibicitiberiu/ytsm
$ docker run chibicitiberiu/ytsm -v /path/to/my/config:/config -v /path/to/my/media:/media
****

The docker compose file is a nice touch but I think it currently has too much "Responsibility" as in the docker image should stand on it's own and the docker compose file should make use of that image and setup other things (nginx/db) so that people can use their own reverse proxy/db but the compose file is an example of how to get things up and running quick (to that end I think the default should be sqlite with an option to use another DB). 



I'm not sure if this is the best place to discuss this and I'm happy to move the discussion to an issue or elsewhere.

**Pull request merged**
